### ISSUE TITLE
Ligature issues

### ISSUE THREAD

**Issue by yanone** [docrepair-fonts/caprasimo-fonts#1]
Metrics of ligatures are an issue:

![Bildschirmfoto 2023-04-12 um 13 34 54](https://user-images.githubusercontent.com/175386/231445366-52e32d5a-9f6a-4857-8f3c-ce97b5bff7bf.jpg)
![Bildschirmfoto 2023-04-12 um 13 33 55](https://user-images.githubusercontent.com/175386/231445372-436f117b-1696-42be-9027-259b77a6083d.jpg)

Please check all other ligatures as well.

**Comment by yanone** [comment]
It's not ligatures alone. It's all kinds of letters.
Also, `ä` isn't the same shape as `a`, for instance.
Please see the sidebearings here (list is not exhaustive):

![Bildschirmfoto 2023-04-14 um 10 42 27](https://user-images.githubusercontent.com/175386/231992544-3e8b5d74-751c-4d0f-8bf4-673060cf3d58.jpg)

**Comment by twardoch** [comment]
Fixed & rebuilt
